services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-service
    ports:
      - "8000:8000"
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow-server
    ports:
      - "8080:8080"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 8080
    volumes:
      - ./mlruns:/mlruns
      - ./mlartifacts:/mlartifacts
